name: GekkeCore
version: '${project.version}'
main: me.nubb.gekkecore.GekkeCore
api-version: '1.21.10'
folia-supported: true
authors: [Nubb__]
softdepend: [ ProtocolLib, WorldEdit ]
description: to cure boredom

commands:

  GekkeCore:
    description: "GekkeCore!"
    usage: "Usage: /gekkecore help"

  Vanish:
    description: "Hide yourself from players!"
    usage: "Usage: /vanish <player>"
    permission: gekkecore.vanish.use
    permission-message: "§cYou dont have permission to execute this command!"

  Vtrades:
    description: "Manage Villager trading"
    usage: "Usage: /vtrades setinstantrestock/setdemandpenalty true/false"
    permission: gekkecore.vtrades.manage
    permission-message: "§cYou dont have permission to execute this command!"

  Socials:
    aliases: [Discord, Youtube, Twitter, Twitch, instagram]
    description: "Manage Villager trading"
    usage: "Usage: /socials"
    permission: gekkecore.socials
    permission-message: "§cYou dont have permission to execute this command!"
